# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#         os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: install ssh
      run: | 
        cat /etc/ssh/sshd_config
        mkdir -p ~/.ssh
        ssh-keygen -f ~/.ssh/id_rsa -P '' -q
        ls -l /etc/ssh/sshd_config.d/ 
        cat /etc/ssh/sshd_config.d/50-cloudimg-settings.conf
        sudo echo "PermitRootLogin yes" >> /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        sudo echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        sudo echo "AuthorizedKeysFile .ssh/authorized_keys" >> /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        sudo echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        sudo sh /etc/init.d/ssh restart
        ls -l ~
        ls -l ~/.ssh
        ssh -tt -i ~/.ssh/id_rsa localhost

