# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

#on:
#  release:
#    types: [published]

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:

  build_linux_wheel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build


  build_manylinux2010_wheel:

    runs-on: ubuntu-latest

    steps:
      - name: Show files
        run: |
          ls -l
          pwd
          ls -l dist


#    - name: convert for centos7
#      uses: docker://quay.io/pypa/manylinux2014_x86_64
#      with:
#        args: auditwheel --help

#    - name: convert for centos8 and later
#      uses: docker://quay.io/pypa/manylinux2014_x86_64
#      with:
#        args: auditwheel --help
#
#    - name: run docker container
#      uses: docker://quay.io/pypa/manylinux2014_x86_64
#      with:
#        args: -v `pwd`:/io auditwheel repair *.whl

#    - name: Publish package
#      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
#      with:
#        user: __token__
#        password: ${{ secrets.PYPI_API_TOKEN }}
